### ISSUE TITLE
improve good type details

### ISSUE THREAD

**Issue by trebor** [trebor/sangai#13]
in the meta-data for the goods the name is sometimes singular like "Public Space", and sometimes plural like "Health Centers".  as a result the front-end can't control how the good is presented.  maybe it would be better if all of the names of the goods were singular.

also, some of these names seem unnecessarily long.  i'm inclined to keep the language as simple as possible, so perhaps in instead of "Educational Institute" use "School", and so forth?  the long terms also take up a lot of screen space.  :)

```json
[
    {
        "id": "roads",
        "name": "Roads"
    },
    {
        "id": "public_water",
        "name": "Public Water Point"
    },
    {
        "id": "public_toilets",
        "name": "Public Toilet"
    },
    {
        "id": "public_space",
        "name": "Public Space"
    },
    {
        "id": "solid_waste",
        "name": "Solid Waste Management"
    },
    {
        "id": "schools",
        "name": "Educational Institutes"
    },
    {
        "id": "health_centers",
        "name": "Health Centers"
    }
]
```

**Comment by sujitmhj** [comment]
@trebor Yeah. We have make changes in this api too. The next version of api will have integer as ID and all labels singular

**Comment by trebor** [comment]
oh great, thank you! :)
