### ISSUE TITLE
Provide option to cluster/uncluster markers for assets

### ISSUE THREAD

**Issue by UpamanyuDatta** [trebor/sangai#8]
When we go to more wards, clustered markers of assets would tell audience roughly how many assets of each type are there in the ward. Having the option to toggle clustering on and off gives this quick taste.

**Comment by trebor** [comment]
done! :)

<img width="578" alt="image" src="https://user-images.githubusercontent.com/12802394/233806862-f719fc9b-199b-4719-a48c-0dd021a86c6c.png">
